name = "TreeShielding"
uuid = "d9a2cea7-bc41-48cd-83f4-1fa9e16975c8"
authors = ["Asger Horn Brorholt"]
version = "0.1.0"

[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Unzip = "41fe7b60-77ed-43a1-b4f0-825fd5a5650d"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
